services:
  sarah-backend:
    build: .
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.sarah-backend.rule=Host(`sarah-api.${TRAEFIK_HOST}`)
      - traefik.http.routers.sarah-backend.entrypoints=websecure
      - traefik.http.routers.sarah-backend.tls.certresolver=letsencrypt
      - traefik.http.services.sarah-backend.loadbalancer.server.port=8000
    env_file:
      - .env
    environment:
      - PORT=8000
